#*************************************************************************
#
#   配置
#
#*************************************************************************

server:
  port: 7891

spring:
  application:
    name: hello-boot
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    username: root
    password: root
    druid:
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: 'SELECT 1'
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat,wall,slf4j
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
  kafka:
    consumer:
      bootstrap-servers: 172.16.200.155:29092
      group-id: group_id
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: 172.16.200.155:29092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer


mybatis-plus:
  type-aliases-package: com.gitee.alona.generator.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
    # 储存枚举索引
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
    auto-mapping-unknown-column-behavior: warning
    # 关闭一级缓存缓存
    local-cache-scope: statement
    # 关闭二级缓存
    cache-enabled: false
  global-config:
    banner: true
    enable-sql-runner: true
    db-config:
      id-type: assign_uuid
      logic-not-delete-value: 1
      logic-delete-field: 0

logging:
  config: classpath:logging-config.xml

management:
  endpoints:
    web:
      exposure:
        include:
          - loggers
          - health
          - beans
          - heapdump

  endpoint:
    beans:
      enabled: true
    loggers:
      enabled: true

# 配置文件加密
# https://mybatis.plus/guide/safety.html
my:
  name: mpw:EJVhnZLYgqDv2wVQ9J9xiA==

forest:
  bean-id: forestConfiguration # 在spring上下文中bean的id, 默认值为forestConfiguration
  backend: okhttp3 # 后端HTTP API： okhttp3
  max-connections: 1000 # 连接池最大连接数，默认值为500
  max-route-connections: 500 # 每个路由的最大连接数，默认值为500
  timeout: 3000 # 请求超时时间，单位为毫秒, 默认值为3000
  connect-timeout: 3000 # 连接超时时间，单位为毫秒, 默认值为2000
  retry-count: 1 # 请求失败后重试次数，默认为0次不重试
  ssl-protocol: SSLv3 # 单向验证的HTTPS的默认SSL协议，默认为SSLv3
  logEnabled: true # 打开或关闭日志，默认为true